const songsList = [
  "Crazier",
  "Babe",
  "Never Grow Up",
  "I'm Only Me When I'm With You",
  "Red",
  "ME!",
  "Forever Winter",
  "marjorie",
  "dorothea",
  "A Perfectly Good Heart",
  "Love Story",
  "The Man",
  "The Other Side Of The Door",
  "evermore",
  "Should've Said No",
  "Superman",
  "This Is Why We Can't Have Nice Things",
  "Stay Stay Stay",
  "seven",
  "Wildest Dreams",
  "All You Had To Do Was Stay",
  "this is me trying",
  "Style",
  "Cruel Summer",
  "Dear John",
  "Girl At Home",
  "it’s time to go",
  "epiphany",
  "The Best Day",
  "Mary's Song (Oh My My My)",
  "Starlight",
  "Cornelia Street",
  "happiness",
  "Delicate",
  "mirrorball",
  "Christmas Tree Farm",
  "Gorgeous",
  "You’re Not Sorry",
  "You Belong With Me",
  "I Forgot That You Existed",
  "Back To December",
  "Bad Blood",
  "ivy",
  "Tell Me Why",
  "right where you left me",
  "invisible string",
  "Change",
  "Picture To Burn",
  "Afterglow",
  "long story short",
  "cowboy like me",
  "Paper Rings",
  "Untouchable",
  "Welcome To New York",
  "peace",
  "Dancing With Our Hands Tied",
  "Teardrops on My Guitar",
  "The Very First Night",
  "coney island",
  "The Moment I Knew",
  "no body",
  " no crime",
  "Miss Americana & The Heartbreak Prince",
  "Mine",
  "New Romantics",
  "Last Christmas",
  "A Place in this World",
  "Sad Beautiful Tragic",
  "I Knew You Were Trouble",
  "Better Than Revenge",
  "All Too Well (10 Minute Version)",
  "Tied Together with a Smile",
  "End Game",
  "Begin Again",
  "exile",
  "the lakes",
  "Look What You Made Me Do",
  "‘tis the damn season",
  "Superstar",
  "The Story Of Us",
  "cardigan",
  "august",
  "Message In A Bottle",
  "Ready For It",
  "hoax",
  "Today Was A Fairytale",
  "Mean",
  "Tim McGraw",
  "Eyes Open",
  "Soon You’ll Get Better",
  "Long Live",
  "Speak Now",
  "This Love",
  "Fifteen",
  "Cold As You",
  "Enchanted",
  "Fearless",
  "Don’t You",
  "Sparks Fly",
  "The Outside",
  "Stay Beautiful",
  "New Year’s Day",
  "the last great american dynasty",
  "The Lucky One",
  "It’s Nice To Have A Friend",
  "I Think He Knows",
  "White Horse",
  "Invisible",
  "How You Get The Girl",
  "Better Man",
  "Out Of The Woods",
  "Clean",
  "Nothing New",
  "Innocent",
  "Come Back...Be Here",
  "Don’t Blame Me",
  "We Were Happy",
  "Holy Ground",
  "London Boy",
  "Wonderland",
  "Mr. Perfectly Fine",
  "the 1",
  "illicit affairs",
  "willow",
  "Silent Night",
  "The Last Time",
  "gold rush",
  "Call It What You Want",
  "betty",
  "Our Song",
  "Death By A Thousand Cuts",
  "You Need To Calm Down",
  "Breathe",
  "Shake It Off",
  "I Did Something Bad",
  "Haunted",
  "Run",
  "So It Goes...",
  "That’s When",
  "State Of Grace",
  "We Are Never Ever Getting Back Together",
  "Last Kiss",
  "I Wish You Would",
  "Forever & Always",
  "Lover",
  "tolerate it",
  "You Are In Love",
  "22",
  "The Archer",
  "I Bet You Think About Me",
  "Blank Space",
  "The Way I Loved You",
  "Jump Then Fall",
  "Dress",
  "Ronan",
  "Daylight",
  "I Almost Do",
  "champagne problems",
  "False God",
  "Come In With The Rain",
  "King Of My Heart",
  "You All Over Me",
  "Everything Has Changed",
  "I Know Places",
  "mad woman",
  "Bye Bye Baby",
  "closure",
  "my tears ricochet",
  "Treacherous",
  "Hey Stephen",
  "Ours",
];

export default songsList;
